name = "fhir_r4p_client_rsvp"
version = "0.7.0"

description = "r4 primitive extensions rsvp client layer - see https://hexdocs.pm/fhir/ "
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
fhir_r4p = { git = "https://github.com/PotatoEMR/fhir_r4p", ref = "8e1a07bc565bddf5fdd546910b58464031fa2575" }
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
rsvp = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
